### ISSUE TITLE
求支持：导出为txt

### ISSUE THREAD

**Issue by LittleTerry** [rerender2021/heard#13]
感谢作者开发这个软件。能否支持导出为txt？现在只能生成srt文件。

**Comment by rerender2021** [comment]
srt文件是纯文本文件，如果需要txt的话，只需要重命名为.txt就可以了。

**Comment by LittleTerry** [comment]
> srt文件是纯文本文件，如果需要txt的话，只需要重命名为.txt就可以了。

感谢您的回复。确实srt是纯文本文件。可能是我没表达清楚，我的意思是，能否去掉时间轴，生成纯TXT文本文件。

**Comment by rerender2021** [comment]
> > srt文件是纯文本文件，如果需要txt的话，只需要重命名为.txt就可以了。
> 
> 感谢您的回复。确实srt是纯文本文件。可能是我没表达清楚，我的意思是，能否去掉时间轴，生成纯TXT文本文件。

可以的，之后加上这个功能，支持指定格式

**Comment by rerender2021** [comment]
已实现，可以试试：https://github.com/rerender2021/heard/releases/tag/preview%2Fformat

**Comment by LittleTerry** [comment]
> 已实现，可以试试：https://github.com/rerender2021/heard/releases/tag/preview%2Fformat

非常感谢您新增这个功能！辛苦了～

**Comment by rerender2021** [comment]
不客气~
