### ISSUE TITLE
识别率和时间轴的问题

### ISSUE THREAD

**Issue by bzsk** [rerender2021/heard#15]
一些2小时的视频，1小时后只会出现“啊”字了，重新识别后效果能有一定的改善。还有就是时间轴有时会对不上，偏快，偏快几句后又恢复正常。

**Comment by bzsk** [comment]
还有就是，能手动指定视频的语言吗？试过一开始识别为日语，但后面就不知道为何都是识别成英文了。

**Comment by rerender2021** [comment]
> 还有就是，能手动指定视频的语言吗？试过一开始识别为日语，但后面就不知道为何都是识别成英文了。

这个可以，见prompt（提示语）：https://rerender2021.github.io/products/heard/#prompt%E6%8F%90%E7%A4%BA%E8%AF%AD

**Comment by rerender2021** [comment]
> 一些2小时的视频，1小时后只会出现“啊”字了，重新识别后效果能有一定的改善。还有就是时间轴有时会对不上，偏快，偏快几句后又恢复正常。

时间轴有时会对不上这个我也偶尔遇到过，我这个只是对openai的whisper简单封装，限于能力，我没法对它改动。

可能之后我去研究下whisper的issue，有没有什么解决办法
